import type {
  Block,
  Domain,
  Vision,
  Routine,
  Weekday,
  Subscription,
  Transaction,
  Reflection,
  StateLogEntry,
  Insight,
  Person,
  WishlistItem,
} from "./types";

export const DOMAINS: Domain[] = [
  {
    id: "business",
    name: "Business",
    emoji: "💼",
    tint: "#E1ECFF",
    momentum: "warm",
    direction: "improving",
    lastEngagement: "today",
    nextAction: "Cold email Reiner",
    streakLabel: "4-day rhythm",
  },
  {
    id: "religion",
    name: "Religion",
    emoji: "🌙",
    tint: "#E5F0E1",
    momentum: "steady",
    direction: "stable",
    lastEngagement: "today",
    nextAction: "Dhuhr in your block",
  },
  {
    id: "learning",
    name: "Learning",
    emoji: "📚",
    tint: "#E6E0FF",
    momentum: "steady",
    direction: "improving",
    lastEngagement: "yesterday",
    nextAction: "20 min on the design extractor",
  },
  {
    id: "fitness",
    name: "Fitness",
    emoji: "🥊",
    tint: "#FFE0E6",
    momentum: "drifting",
    direction: "improving",
    lastEngagement: "2 days ago",
    nextAction: "Gym tonight, 60 min",
  },
  {
    id: "home",
    name: "Home",
    emoji: "🏠",
    tint: "#DDF0F5",
    momentum: "steady",
    direction: "stable",
    lastEngagement: "yesterday",
    nextAction: "Laundry + balcony",
  },
  {
    id: "food",
    name: "Food",
    emoji: "🍽️",
    tint: "#FFF3E0",
    momentum: "quiet",
    direction: "stable",
    lastEngagement: "today",
    nextAction: "Prep tonight's chicken bowl",
  },
];

export const SEED_BLOCKS: Block[] = [
  {
    id: "b1",
    title: "Webuild — finish Dr. Lashin landing draft",
    domain: "business",
    durationMin: 60,
    status: "pending",
    accumulatedMs: 0,
    order: 0,
    scheduledFor: "today",
    step: {
      kind: "outline",
      items: [
        "Write hero headline",
        "Draft value prop section",
        "Add testimonial placeholders",
        "Review and publish",
      ],
      current: 1,
    },
  },
  {
    id: "b2",
    title: "Quran — read & reflect",
    domain: "religion",
    durationMin: 20,
    status: "pending",
    accumulatedMs: 0,
    order: 1,
    scheduledFor: "today",
    step: {
      kind: "verses",
      items: [
        "Al-Baqarah 255 (Ayat al-Kursi)",
        "Al-Ikhlas",
        "Al-Falaq",
        "An-Nas",
      ],
      current: 0,
    },
  },
  {
    id: "b3",
    title: "Design extractor — research Framer templates",
    domain: "learning",
    durationMin: 45,
    status: "pending",
    accumulatedMs: 0,
    order: 2,
    scheduledFor: "today",
    mode: "theory" as const,
  },
  {
    id: "b4",
    title: "Cold emails — Personalvermittler batch",
    domain: "business",
    durationMin: 30,
    status: "pending",
    accumulatedMs: 0,
    order: 3,
    scheduledFor: "today",
    mode: "application" as const,
  },
  {
    id: "b5",
    title: "Gym — push session",
    domain: "fitness",
    durationMin: 60,
    status: "pending",
    accumulatedMs: 0,
    order: 4,
    scheduledFor: "today",
    step: {
      kind: "sets",
      items: [
        "Bench press 4×8",
        "Overhead press 3×10",
        "Tricep dips 3×12",
        "Lateral raises 3×15",
      ],
      current: 0,
    },
  },
  {
    id: "b6",
    title: "Home — laundry, clear desk",
    domain: "home",
    durationMin: 25,
    status: "pending",
    accumulatedMs: 0,
    order: 5,
    scheduledFor: "today",
  },
  // Food blocks with ingredients for meal + shopping
  {
    id: "bf1",
    title: "Breakfast — oats & berries",
    domain: "food",
    durationMin: 15,
    status: "pending",
    accumulatedMs: 0,
    order: 6,
    scheduledFor: "today",
    step: {
      kind: "recipe",
      items: [
        "Cook rolled oats 5 min",
        "Add frozen berries",
        "Drizzle honey",
        "Serve warm",
      ],
      current: 0,
    },
    meta: {
      ingredients: ["rolled oats", "frozen berries", "honey", "milk"],
      mealSlot: "breakfast",
    },
  },
  {
    id: "bf2",
    title: "Lunch — chicken rice bowl",
    domain: "food",
    durationMin: 30,
    status: "pending",
    accumulatedMs: 0,
    order: 7,
    scheduledFor: "today",
    step: {
      kind: "recipe",
      items: [
        "Cook basmati rice",
        "Season & pan-fry chicken breast",
        "Slice cucumber & tomato",
        "Assemble bowl with tahini",
      ],
      current: 0,
    },
    meta: {
      ingredients: [
        "chicken breast",
        "basmati rice",
        "cucumber",
        "tomato",
        "tahini",
        "lemon",
        "garlic",
      ],
      mealSlot: "lunch",
    },
  },
  {
    id: "bf3",
    title: "Dinner — salmon & vegetables",
    domain: "food",
    durationMin: 35,
    status: "pending",
    accumulatedMs: 0,
    order: 8,
    scheduledFor: "today",
    step: {
      kind: "recipe",
      items: [
        "Season salmon with olive oil & herbs",
        "Roast broccoli & sweet potato",
        "Pan-sear salmon 4 min each side",
        "Plate and squeeze lemon",
      ],
      current: 0,
    },
    meta: {
      ingredients: [
        "salmon fillet",
        "broccoli",
        "sweet potato",
        "olive oil",
        "lemon",
        "fresh dill",
      ],
      mealSlot: "dinner",
    },
  },
];

export const SEED_VISIONS: Vision[] = [
  {
    id: "v1",
    title: "Webuild",
    blurb:
      "The website + solutions company. Templates → leads → close → automate.",
    domainId: "business",
    tint: "#E1ECFF",
    description:
      "A site shop that ships fast, beautiful, near-free websites to founders and small teams — powered by templates, lead gen, and a closing pipeline that quietly compounds in the background.",
    anchorLine: "Every block on Webuild moves the pipeline forward.",
    nextMove: "Send 10 cold emails to Personalvermittler this week.",
    threads: [
      {
        id: "t1",
        title: "Templates engine",
        sub: "The reusable spine — Framer, Webflow, code",
      },
      {
        id: "t2",
        title: "Lead generation",
        sub: "Where the right founders find us",
      },
      {
        id: "t3",
        title: "Cold email automation",
        sub: "A patient, quiet outbound loop",
      },
      {
        id: "t4",
        title: "Closing pipeline",
        sub: "Calls, scope, signed — without friction",
      },
      {
        id: "t5",
        title: "Webuild.solutions",
        sub: "The faces of the same engine",
      },
    ],
  },
  {
    id: "v2",
    title: "Jarvis × Claude",
    blurb:
      "Co-evolution engine. High-level brain piecing it all together via Notion.",
    domainId: "learning",
    tint: "#E6E0FF",
    nextMove: "Wire today's blocks into Notion and see the pattern.",
    threads: [
      {
        id: "t1",
        title: "Notion as memory",
        sub: "The external brain that persists",
      },
      {
        id: "t2",
        title: "Claude as collaborator",
        sub: "Real-time thinking partner",
      },
    ],
  },
  {
    id: "v3",
    title: "Second Brain",
    blurb: "The personal database that thinks the way you think.",
    domainId: "learning",
    tint: "#E6E0FF",
    nextMove: "Capture three insights from today into the system.",
  },
  {
    id: "v4",
    title: "Dr. Lashin platform",
    blurb: "Kentnissprüfung site, app, and content engine.",
    domainId: "business",
    tint: "#E1ECFF",
    nextMove: "Ship the landing page draft by end of week.",
    threads: [
      {
        id: "t1",
        title: "Landing page",
        sub: "Where doctors land and convert",
      },
      {
        id: "t2",
        title: "Content engine",
        sub: "Questions, guides, prep material",
      },
    ],
  },
  {
    id: "v5",
    title: "Strong rhythm in fitness",
    blurb: "Combat sports + gym, weekly cadence that holds.",
    domainId: "fitness",
    tint: "#FFE0E6",
    nextMove: "Show up to the gym three times this week.",
    deadline: "2026-07-28",
    targetMetric: "3 gym sessions per week for 8 consecutive weeks",
  },
  {
    id: "v6",
    title: "Stable religious practice",
    blurb: "Five prayers on time, Quran daily, Islamic learning weekly.",
    domainId: "religion",
    tint: "#E5F0E1",
    anchorLine: "Prayer is the anchor everything else bends around.",
    nextMove: "Complete Dhuhr and the Quran block today.",
  },
  {
    id: "v7",
    title: "Plan for Life",
    blurb: "The vision document for everything across every domain.",
    domainId: "learning",
    tint: "#E6E0FF",
    nextMove: "Write one paragraph about where you want to be in 3 years.",
  },
];

export const SEED_ROUTINES: Routine[] = [
  {
    id: "r1",
    name: "Weekday morning",
    color: "weekday",
    days: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    cadenceDescription: "Every weekday, Monday through Friday",
    streakPhrase: "4 weeks running",
    blocks: [
      {
        id: "rb1",
        title: "Quran · read & reflect",
        domain: "religion",
        durationMin: 20,
        order: 0,
      },
      {
        id: "rb2",
        title: "Webuild · deep work",
        domain: "business",
        durationMin: 90,
        order: 1,
      },
      {
        id: "rb3",
        title: "Cold emails",
        domain: "business",
        durationMin: 30,
        order: 2,
      },
      {
        id: "rb4",
        title: "Learning sprint",
        domain: "learning",
        durationMin: 45,
        order: 3,
      },
      {
        id: "rb5",
        title: "Gym · push session",
        domain: "fitness",
        durationMin: 60,
        order: 4,
      },
    ],
  },
  {
    id: "r2",
    name: "Recovery day",
    color: "recovery",
    days: ["Sat"],
    cadenceDescription: "Saturday — rest and reset",
    streakPhrase: "Every week",
    blocks: [
      {
        id: "rb1",
        title: "Quran · read & reflect",
        domain: "religion",
        durationMin: 20,
        order: 0,
      },
      {
        id: "rb2",
        title: "Home · reset & tidy",
        domain: "home",
        durationMin: 60,
        order: 1,
      },
      {
        id: "rb3",
        title: "Light walk",
        domain: "fitness",
        durationMin: 30,
        order: 2,
      },
    ],
  },
  {
    id: "r3",
    name: "Friday cycle",
    color: "friday",
    days: ["Fri"],
    cadenceDescription: "Every Friday afternoon",
    blocks: [
      {
        id: "rb1",
        title: "Jumu'ah prep + prayer",
        domain: "religion",
        durationMin: 40,
        order: 0,
      },
      {
        id: "rb2",
        title: "Week review",
        domain: "learning",
        durationMin: 30,
        order: 1,
      },
    ],
  },
  {
    id: "r4",
    name: "Sunday slow",
    color: "sunday",
    days: ["Sun"],
    cadenceDescription: "Sunday — slow and deliberate",
    blocks: [
      {
        id: "rb1",
        title: "Quran · long session",
        domain: "religion",
        durationMin: 45,
        order: 0,
      },
      {
        id: "rb2",
        title: "Plan next week",
        domain: "learning",
        durationMin: 45,
        order: 1,
      },
    ],
  },
];

export const SEED_WEEK_ASSIGNMENTS: Record<Weekday, string | null> = {
  Mon: "r1",
  Tue: "r1",
  Wed: "r1",
  Thu: "r1",
  Fri: "r1",
  Sat: "r2",
  Sun: null,
};

export const SEED_SUBSCRIPTIONS: Subscription[] = [
  {
    id: "sub1",
    name: "Spotify",
    amountCents: 1099,
    currency: "USD",
    cadence: "monthly",
    nextChargeISO: "2026-05-18",
    category: "music",
  },
  {
    id: "sub2",
    name: "GitHub Pro",
    amountCents: 400,
    currency: "USD",
    cadence: "monthly",
    nextChargeISO: "2026-05-22",
    category: "software",
  },
  {
    id: "sub3",
    name: "ChatGPT Plus",
    amountCents: 2000,
    currency: "USD",
    cadence: "monthly",
    nextChargeISO: "2026-05-14",
    category: "software",
  },
];

const thisMonthISO = "2026-05-";
export const SEED_TRANSACTIONS: Transaction[] = [
  {
    id: "tx1",
    kind: "expense",
    amountCents: 5400,
    currency: "USD",
    dateISO: `${thisMonthISO}02`,
    category: "food",
    note: "Grocery run",
    source: "manual",
  },
  {
    id: "tx2",
    kind: "expense",
    amountCents: 8900,
    currency: "USD",
    dateISO: `${thisMonthISO}04`,
    category: "gym",
    note: "Monthly gym membership",
    source: "manual",
  },
  {
    id: "tx3",
    kind: "income",
    amountCents: 250000,
    currency: "USD",
    dateISO: `${thisMonthISO}01`,
    category: "freelance",
    note: "Webuild client project",
    source: "manual",
  },
  {
    id: "tx4",
    kind: "income",
    amountCents: 42000,
    currency: "USD",
    dateISO: `${thisMonthISO}03`,
    category: "dividend",
    note: "ETF dividend",
    source: "manual",
  },
];

export const SEED_REFLECTIONS: Reflection[] = [
  {
    id: "ref1",
    dateISO: "2026-05-05",
    worked:
      "Deep work session on the Dr. Lashin landing page was uninterrupted — got the hero drafted.",
    shifted:
      "Gym moved to evening, which actually felt better than the morning slot.",
    firstMove: "Send the landing page draft to review first thing.",
  },
];

export const SEED_STATE_LOG: StateLogEntry[] = [
  { id: "sl1", ts: Date.now() - 3 * 3600_000, mark: "focused" },
  { id: "sl2", ts: Date.now() - 1 * 3600_000, mark: "wired" },
];

export const SEED_INSIGHTS: Insight[] = [
  {
    id: "ins1",
    text: "Consistency compounds faster than intensity. Showing up every day, even for 20 minutes, builds more than a single heroic session.",
    source: "Atomic Habits",
    domainId: "learning",
    capturedAt: Date.now() - 2 * 86400_000,
  },
  {
    id: "ins2",
    text: "The goal is not to be perfect at prayer — it is to return quickly when you drift.",
    domainId: "religion",
    capturedAt: Date.now() - 86400_000,
  },
];

export const SEED_WISHLIST: WishlistItem[] = [
  {
    id: "w1",
    name: "Atomic Habits",
    expectedAmountCents: 2400,
    currency: "USD",
    priority: "low",
    category: "books",
    status: "wanted",
    createdAt: Date.now() - 7 * 86400_000,
  },
  {
    id: "w2",
    name: "Resistance bands set",
    expectedAmountCents: 8900,
    currency: "USD",
    priority: "medium",
    category: "gear",
    status: "wanted",
    createdAt: Date.now() - 5 * 86400_000,
  },
  {
    id: "w3",
    name: "USB-C hub (Anker 9-in-1)",
    expectedAmountCents: 14500,
    currency: "USD",
    priority: "high",
    category: "tools",
    status: "wanted",
    createdAt: Date.now() - 3 * 86400_000,
  },
  {
    id: "w4",
    name: "Ali Abdaal productivity course",
    expectedAmountCents: 39900,
    currency: "USD",
    priority: "medium",
    category: "experiences",
    status: "wanted",
    createdAt: Date.now() - 2 * 86400_000,
  },
  {
    id: "w5",
    name: "Mechanical keyboard (Keychron K2)",
    expectedAmountCents: 9900,
    currency: "USD",
    priority: "low",
    category: "tools",
    status: "wanted",
    createdAt: Date.now() - 86400_000,
  },
];

export const SEED_PEOPLE: Person[] = [
  {
    id: "p1",
    name: "Mom",
    relation: "Family",
    lastTouchedISO: "2026-04-28",
    nextMove: "Call this weekend — ask about the trip.",
  },
  {
    id: "p2",
    name: "Karim",
    relation: "Business mentor",
    lastTouchedISO: "2026-04-20",
    nextMove: "Share the Webuild pipeline update and ask for feedback.",
  },
  {
    id: "p3",
    name: "Faris",
    relation: "Gym partner",
    lastTouchedISO: "2026-05-03",
    nextMove: "Confirm Thursday push session.",
  },
];
