import type { Block, Domain, Vision } from "./types";

export const DOMAINS: Domain[] = [
  {
    id: "business",
    name: "Business",
    emoji: "🚀",
    tint: "#FFE8D6",
    momentum: "strong",
    direction: "improving",
    lastEngagement: "today",
    nextAction: "Cold email Reiner",
  },
  {
    id: "religion",
    name: "Religion",
    emoji: "🕌",
    tint: "#E5F0E1",
    momentum: "stable",
    direction: "stable",
    lastEngagement: "today",
    nextAction: "Dhuhr in your block",
  },
  {
    id: "learning",
    name: "Learning",
    emoji: "📚",
    tint: "#E6E0FF",
    momentum: "stable",
    direction: "improving",
    lastEngagement: "yesterday",
    nextAction: "20 min on the design extractor",
  },
  {
    id: "fitness",
    name: "Fitness",
    emoji: "🥊",
    tint: "#FFE0E6",
    momentum: "weak",
    direction: "improving",
    lastEngagement: "2 days ago",
    nextAction: "Gym tonight, 60 min",
  },
  {
    id: "home",
    name: "Home",
    emoji: "🏠",
    tint: "#DDF0F5",
    momentum: "stable",
    direction: "stable",
    lastEngagement: "yesterday",
    nextAction: "Laundry + balcony",
  },
];

export const SEED_BLOCKS: Block[] = [
  {
    id: "b1",
    title: "Webuild — finish Dr. Lashin landing draft",
    domainId: "business",
    durationMin: 60,
    status: "idle",
    accumulatedMs: 0,
    order: 0,
  },
  {
    id: "b2",
    title: "Quran — read & reflect",
    domainId: "religion",
    durationMin: 20,
    status: "idle",
    accumulatedMs: 0,
    order: 1,
  },
  {
    id: "b3",
    title: "Design extractor — research Framer templates",
    domainId: "learning",
    durationMin: 45,
    status: "idle",
    accumulatedMs: 0,
    order: 2,
  },
  {
    id: "b4",
    title: "Cold emails — Personalvermittler batch",
    domainId: "business",
    durationMin: 30,
    status: "idle",
    accumulatedMs: 0,
    order: 3,
  },
  {
    id: "b5",
    title: "Gym — push session",
    domainId: "fitness",
    durationMin: 60,
    status: "idle",
    accumulatedMs: 0,
    order: 4,
  },
  {
    id: "b6",
    title: "Home — laundry, clear desk",
    domainId: "home",
    durationMin: 25,
    status: "idle",
    accumulatedMs: 0,
    order: 5,
  },
];

export const SEED_VISIONS: Vision[] = [
  {
    id: "v1",
    title: "Webuild",
    blurb:
      "The website + solutions company. Templates → leads → close → automate.",
    domainId: "business",
    tint: "#FFE8D6",
  },
  {
    id: "v2",
    title: "Jarvis × Claude",
    blurb:
      "Co-evolution engine. High-level brain piecing it all together via Notion.",
    domainId: "learning",
    tint: "#E6E0FF",
  },
  {
    id: "v3",
    title: "Second Brain",
    blurb: "The personal database that thinks the way you think.",
    domainId: "learning",
    tint: "#E6E0FF",
  },
  {
    id: "v4",
    title: "Dr. Lashin platform",
    blurb: "Kentnissprüfung site, app, and content engine.",
    domainId: "business",
    tint: "#FFE8D6",
  },
  {
    id: "v5",
    title: "Strong rhythm in fitness",
    blurb: "Combat sports + gym, weekly cadence that holds.",
    domainId: "fitness",
    tint: "#FFE0E6",
  },
  {
    id: "v6",
    title: "Stable religious practice",
    blurb: "Five prayers on time, Quran daily, Islamic learning weekly.",
    domainId: "religion",
    tint: "#E5F0E1",
  },
  {
    id: "v7",
    title: "Plan for Life",
    blurb: "The vision document for everything across every domain.",
    domainId: "learning",
    tint: "#E6E0FF",
  },
];
