import type { Block, Domain, Vision, Routine, Weekday } from "./types";

export const DOMAINS: Domain[] = [
  {
    id: "business",
    name: "Business",
    emoji: "🚀",
    tint: "#FFE8D6",
    momentum: "strong",
    direction: "improving",
    lastEngagement: "today",
    nextAction: "Cold email Reiner",
    streakLabel: "4-day rhythm",
  },
  {
    id: "religion",
    name: "Religion",
    emoji: "🕌",
    tint: "#E5F0E1",
    momentum: "stable",
    direction: "stable",
    lastEngagement: "today",
    nextAction: "Dhuhr in your block",
  },
  {
    id: "learning",
    name: "Learning",
    emoji: "📚",
    tint: "#E6E0FF",
    momentum: "stable",
    direction: "improving",
    lastEngagement: "yesterday",
    nextAction: "20 min on the design extractor",
  },
  {
    id: "fitness",
    name: "Fitness",
    emoji: "🥊",
    tint: "#FFE0E6",
    momentum: "weak",
    direction: "improving",
    lastEngagement: "2 days ago",
    nextAction: "Gym tonight, 60 min",
  },
  {
    id: "home",
    name: "Home",
    emoji: "🏠",
    tint: "#DDF0F5",
    momentum: "stable",
    direction: "stable",
    lastEngagement: "yesterday",
    nextAction: "Laundry + balcony",
  },
];

export const SEED_BLOCKS: Block[] = [
  {
    id: "b1",
    title: "Webuild — finish Dr. Lashin landing draft",
    domainId: "business",
    durationMin: 60,
    status: "idle",
    accumulatedMs: 0,
    order: 0,
    step: { current: 2, total: 4 },
    focusType: "deep focus",
  },
  {
    id: "b2",
    title: "Quran — read & reflect",
    domainId: "religion",
    durationMin: 20,
    status: "idle",
    accumulatedMs: 0,
    order: 1,
  },
  {
    id: "b3",
    title: "Design extractor — research Framer templates",
    domainId: "learning",
    durationMin: 45,
    status: "idle",
    accumulatedMs: 0,
    order: 2,
  },
  {
    id: "b4",
    title: "Cold emails — Personalvermittler batch",
    domainId: "business",
    durationMin: 30,
    status: "idle",
    accumulatedMs: 0,
    order: 3,
  },
  {
    id: "b5",
    title: "Gym — push session",
    domainId: "fitness",
    durationMin: 60,
    status: "idle",
    accumulatedMs: 0,
    order: 4,
  },
  {
    id: "b6",
    title: "Home — laundry, clear desk",
    domainId: "home",
    durationMin: 25,
    status: "idle",
    accumulatedMs: 0,
    order: 5,
  },
];

export const SEED_VISIONS: Vision[] = [
  {
    id: "v1",
    title: "Webuild",
    blurb:
      "The website + solutions company. Templates → leads → close → automate.",
    domainId: "business",
    tint: "#FFE8D6",
    description:
      "A site shop that ships fast, beautiful, near-free websites to founders and small teams — powered by templates, lead gen, and a closing pipeline that quietly compounds in the background. The work flows in. The work flows out.",
    threads: [
      {
        id: "t1",
        title: "Templates engine",
        sub: "The reusable spine — Framer, Webflow, code",
      },
      {
        id: "t2",
        title: "Lead generation",
        sub: "Where the right founders find us",
      },
      {
        id: "t3",
        title: "Cold email automation",
        sub: "A patient, quiet outbound loop",
      },
      {
        id: "t4",
        title: "Closing pipeline",
        sub: "Calls, scope, signed — without friction",
      },
      {
        id: "t5",
        title: "Webuild.solutions",
        sub: "The faces of the same engine",
      },
    ],
  },
  {
    id: "v2",
    title: "Jarvis × Claude",
    blurb:
      "Co-evolution engine. High-level brain piecing it all together via Notion.",
    domainId: "learning",
    tint: "#E6E0FF",
    threads: [
      {
        id: "t1",
        title: "Notion as memory",
        sub: "The external brain that persists",
      },
      {
        id: "t2",
        title: "Claude as collaborator",
        sub: "Real-time thinking partner",
      },
    ],
  },
  {
    id: "v3",
    title: "Second Brain",
    blurb: "The personal database that thinks the way you think.",
    domainId: "learning",
    tint: "#E6E0FF",
  },
  {
    id: "v4",
    title: "Dr. Lashin platform",
    blurb: "Kentnissprüfung site, app, and content engine.",
    domainId: "business",
    tint: "#FFE8D6",
    threads: [
      {
        id: "t1",
        title: "Landing page",
        sub: "Where doctors land and convert",
      },
      {
        id: "t2",
        title: "Content engine",
        sub: "Questions, guides, prep material",
      },
    ],
  },
  {
    id: "v5",
    title: "Strong rhythm in fitness",
    blurb: "Combat sports + gym, weekly cadence that holds.",
    domainId: "fitness",
    tint: "#FFE0E6",
  },
  {
    id: "v6",
    title: "Stable religious practice",
    blurb: "Five prayers on time, Quran daily, Islamic learning weekly.",
    domainId: "religion",
    tint: "#E5F0E1",
  },
  {
    id: "v7",
    title: "Plan for Life",
    blurb: "The vision document for everything across every domain.",
    domainId: "learning",
    tint: "#E6E0FF",
  },
];

export const SEED_ROUTINES: Routine[] = [
  {
    id: "r1",
    name: "Weekday morning",
    color: "weekday",
    days: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    blocks: [
      {
        id: "rb1",
        title: "Quran · read & reflect",
        domainId: "religion",
        durationMin: 20,
        adjustedMin: 0,
        order: 0,
        step: undefined,
        focusType: undefined,
      },
      {
        id: "rb2",
        title: "Webuild · deep work",
        domainId: "business",
        durationMin: 90,
        adjustedMin: 0,
        order: 1,
        step: undefined,
        focusType: "deep focus",
      },
      {
        id: "rb3",
        title: "Cold emails",
        domainId: "business",
        durationMin: 30,
        adjustedMin: 0,
        order: 2,
        step: undefined,
        focusType: undefined,
      },
      {
        id: "rb4",
        title: "Learning sprint",
        domainId: "learning",
        durationMin: 45,
        adjustedMin: 0,
        order: 3,
        step: undefined,
        focusType: undefined,
      },
      {
        id: "rb5",
        title: "Gym · push session",
        domainId: "fitness",
        durationMin: 60,
        adjustedMin: 0,
        order: 4,
        step: undefined,
        focusType: undefined,
      },
    ],
  },
  {
    id: "r2",
    name: "Recovery day",
    color: "recovery",
    days: ["Sat"],
    blocks: [
      {
        id: "rb1",
        title: "Quran · read & reflect",
        domainId: "religion",
        durationMin: 20,
        adjustedMin: 0,
        order: 0,
        step: undefined,
        focusType: undefined,
      },
      {
        id: "rb2",
        title: "Home · reset & tidy",
        domainId: "home",
        durationMin: 60,
        adjustedMin: 0,
        order: 1,
        step: undefined,
        focusType: undefined,
      },
      {
        id: "rb3",
        title: "Light walk",
        domainId: "fitness",
        durationMin: 30,
        adjustedMin: 0,
        order: 2,
        step: undefined,
        focusType: undefined,
      },
    ],
  },
  {
    id: "r3",
    name: "Friday cycle",
    color: "friday",
    days: ["Fri"],
    blocks: [
      {
        id: "rb1",
        title: "Jumu'ah prep + prayer",
        domainId: "religion",
        durationMin: 40,
        adjustedMin: 0,
        order: 0,
        step: undefined,
        focusType: undefined,
      },
      {
        id: "rb2",
        title: "Week review",
        domainId: "learning",
        durationMin: 30,
        adjustedMin: 0,
        order: 1,
        step: undefined,
        focusType: undefined,
      },
    ],
  },
  {
    id: "r4",
    name: "Sunday slow",
    color: "sunday",
    days: ["Sun"],
    blocks: [
      {
        id: "rb1",
        title: "Quran · long session",
        domainId: "religion",
        durationMin: 45,
        adjustedMin: 0,
        order: 0,
        step: undefined,
        focusType: undefined,
      },
      {
        id: "rb2",
        title: "Plan next week",
        domainId: "learning",
        durationMin: 45,
        adjustedMin: 0,
        order: 1,
        step: undefined,
        focusType: undefined,
      },
    ],
  },
];

export const SEED_WEEK_ASSIGNMENTS: Record<Weekday, string | null> = {
  Mon: "r1",
  Tue: "r1",
  Wed: "r1",
  Thu: "r1",
  Fri: "r1",
  Sat: "r2",
  Sun: null,
};
